<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="0.20.0" PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zubr.Compiler.CSharp\Zubr.Compiler.CSharp.csproj" />
    <ProjectReference Include="..\Zubr.Compiler\Zubr.Compiler.csproj" />
  </ItemGroup>

</Project>
